apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-web
  template:
    metadata:
      labels:
        app: registry-web
    spec:
      containers:
        - name: registry-web
          image: konradkleine/docker-registry-frontend:v2
          ports:
          - name: web
            containerPort: 80
          env:
          - name: ENV_DOCKER_REGISTRY_HOST
            value: "registry"
          - name: ENV_DOCKER_REGISTRY_PORT
            value: "5000"
---
kind: Service
apiVersion: v1
metadata:
  name: registry-web
  labels:
    app: registry-web
spec:
  selector:
    app: registry-web
  ports:
  - name: web
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-web
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: registry.k8s.go-nerd.de
    http:
      paths:
      - path: /
        backend:
          serviceName: registry-web
          servicePort: web