apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    debug = true
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
      [entryPoints.traefik]
      address = ":8080"
    [kubernetes]
    [acme]
    email = "${ACME_EMAIL}"
    storage = "/acme/acme.json"
    entryPoint = "https"
    onHostRule = true
    acmeLogging = true
      [acme.dnsChallenge]
      provider = "cloudflare"
    [api]
      entryPoint = "traefik"
      dashboard = true
    [[acme.domains]]
      main = "*.${DNS_DOMAIN}"