FROM ubuntu:xenial

RUN apt-get update \
    && apt-get -y install git libssl-dev libpam0g-dev zlib1g-dev dh-autoreconf

RUN git clone https://github.com/shellinabox/shellinabox.git \
    && cd shellinabox \
    && autoreconf -i \
    && ./configure \
    && make