pipeline:
  build:
    image: docker:18.06
    environment:
    - REGISTRY=hub.dille.io
    commands:
    - echo "$${REGISTRY_PASS}" | docker login --username $${REGISTRY_USER} --password-stdin $${REGISTRY}
    - docker build --build-arg CI_BUILD_NUMBER --tag $${REGISTRY}/${CI_REPO_NAME}:${CI_BUILD_NUMBER} --tag $${REGISTRY}/${CI_REPO_NAME}:latest .
    - docker push $${REGISTRY}/${CI_REPO_NAME}:${CI_BUILD_NUMBER}
    - docker push $${REGISTRY}/${CI_REPO_NAME}:latest
    - docker logout $${REGISTRY}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ REGISTRY_USER, REGISTRY_PASS ]