pipeline:

  build:
    image: docker:18.06
    secrets: [ REGISTRY_USER, REGISTRY_PASS ]
    commands:
    - docker ps -aq --filter name=shellinabox | xargs -r docker rm -f
    - docker build --file Dockerfile.build --tag shellinabox:builder .
    - docker create --name shellinabox shellinabox:builder
    - docker cp shellinabox:/shellinabox/shellinaboxd .
    - docker cp shellinabox:/shellinabox/shellinabox/color.css .
    - docker cp shellinabox:/shellinabox/shellinabox/monochrome.css .
    - docker cp shellinabox:/shellinabox/shellinabox/black-on-white.css .
    - docker cp shellinabox:/shellinabox/shellinabox/white-on-black.css .
    - docker ps -aq --filter name=shellinabox | xargs -r docker rm -f
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  package:
    image: docker:18.06
    secrets: [ REGISTRY_USER, REGISTRY_PASS ]
    environment:
    - REGISTRY=hub.dille.io
    commands:
    - echo "$${REGISTRY_PASS}" | docker login --username $${REGISTRY_USER} --password-stdin $${REGISTRY}
    - docker build --tag $${REGISTRY}/${CI_REPO_NAME}:${CI_BUILD_NUMBER} --tag $${REGISTRY}/${CI_REPO_NAME}:dev .
    - docker push $${REGISTRY}/${CI_REPO_NAME}:${CI_BUILD_NUMBER}
    - docker push $${REGISTRY}/${CI_REPO_NAME}:dev
    - docker logout $${REGISTRY}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  test:
    image: docker:18.06
    secrets: [ REGISTRY_USER, REGISTRY_PASS ]
    environment:
    - REGISTRY=hub.dille.io
    commands:
    - apk update
    - apk add curl
    - echo "$${REGISTRY_PASS}" | docker login --username $${REGISTRY_USER} --password-stdin $${REGISTRY}
    - docker ps -aq --filter name=shellinabox | xargs -r docker rm -f
    - docker run -d --name shellinabox $${REGISTRY}/${CI_REPO_NAME}:${CI_BUILD_NUMBER}
    - sleep 10
    - curl --fail $(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' shellinabox):4200
    - docker ps -aq --filter name=shellinabox | xargs -r docker rm -f
    - docker logout $${REGISTRY}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock